name: Android CI (JDK 21)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: android-actions/setup-android@v3

      - run: |
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - uses: gradle/actions/setup-gradle@v4

      - run: chmod +x gradlew

      - run: ./gradlew --no-daemon clean :app:assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk-jdk21
          path: app/build/outputs/apk/debug/app-debug.apk
